server:
  port: 8888

spring:
  application:
    name: insite-config-service
  config:
    import: optional:file:.env[.proerties]
    rabbitmq:
    host: insite-rabbit
    port: 5672
    username:  guest
    password: guest
  cloud:
    config:
      server:
        git:
          uri: ${GIT_URI}
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
management:
  endpoints:
    web:
      exposure:
        include: health,busrefresh
