server:
  port: 8888

spring:
  application:
    name: insite-config-service
  rabbitmq:
    host: insite-rabbit
    port: 5672
    username:  guest
    password: guest
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DHKIM-0511/insite-config.git
          username: DHKIM-0511@github.com
          password: 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
management:
  endpoints:
    web:
      exposure:
        include: health,busrefresh
