version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "./mongodb/data:/data/db"
    container_name: mongodb-insite
  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    volumes:
      - "./influxdb/data:/var/lib/influxdb2"
      - "./influxdb/config:/etc/influxdb2"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=thirtyman
      - DOCKER_INFLUXDB_INIT_PASSWORD=behappy1234
      - DOCKER_INFLUXDB_INIT_ORG=thirty
      - DOCKER_INFLUXDB_INIT_BUCKET=insite
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=behappy1234
    container_name: influxdb-insite

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    container_name: zookeeper-insite

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka-insite
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "kafka-connect-configs:1:1,kafka-connect-offsets:1:1,kafka-connect-status:1:1" # 'data' 토픽, 1개의 파티션, 3의 복제 계수
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    container_name: kafka-insite

  kafka-connect:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka-insite:9092
      CONNECT_REST_ADVERTISED_HOST_NAME: kafka-connect
      CONNECT_GROUP_ID: kafka-connect-group
      CONNECT_CONFIG_STORAGE_TOPIC: kafka-connect-configs
      CONNECT_OFFSET_STORAGE_TOPIC: kafka-connect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: kafka-connect-status
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_REST_PORT: 8083
    volumes:
      - ./kafka-connect-data:/var/lib/kafka/data
      - ./kafka-connect-logs:/var/log/kafka
    depends_on:
      - kafka
    container_name: kafka-connect-insite
