server:
  port: 8083
  servlet:
    context-path: /api/v1

spring:
  application:
    name: insite-member-service
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-insite:3306/insite?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8
    username: thirty
    password: behappy1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        format_sql: true
  data:
    redis:
      host: redis-insite
      port: 6379
      password: behappy1234
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

eureka:
 client:
   register-with-eureka: true
   fetch-registry: true
   service-url:
     defaultZone: http://k9a701.p.ssafy.io:8761/eureka

kakao:
  url: https://takeinsite:3001/login
  secret: 2bc86d2cbd61f0e2739114ea6d33b5b6
